### ISSUE TITLE
How to run this SwiftUI project with Swift development toolchain?

### ISSUE THREAD

**Issue by MarcoEidinger** [peterfriese/Swift-Async-Await-Experiments#2]
Hi Peter,

great[ blog post](https://peterfriese.dev/async-await-in-swiftui/) and project!

I am able to compile but I am not able to run this project. I am using Xcode 12.4 and toolchain `swift-DEVELOPMENT-SNAPSHOT-2021-03-07-a.xctoolchain`.

> dyld: Symbol not found: _$sSo12NSFileHandleC10FoundationE9readToEndAC4DataVSgyKF
  Referenced from: /System/Library/Frameworks/SwiftUI.framework/SwiftUI
  Expected in: /Library/Developer/Toolchains/swift-DEVELOPMENT-SNAPSHOT-2021-03-07-a.xctoolchain/usr/lib/swift/iphonesimulator/libswiftFoundation.dylib
 in /System/Library/Frameworks/SwiftUI.framework/SwiftUI

Apparently I am not alone when it comes to running the Swift development toolchain in SwiftUI projects: https://forums.swift.org/t/swift-development-toolchain-crashes-in-swiftui-projects/43592 

I was wondering how you were able to overcome this issue?

**Comment by peterfriese** [comment]
Hi Marco,

just delete the offending file (yeah, I know - it sounds counterintuitive...):

`rm /Library/Developer/Toolchains/swift-DEVELOPMENT-SNAPSHOT-2021-03-05-a.xctoolchain/usr/lib/swift/iphonesimulator/libswiftFoundation.dylib`

I filed a radar: FB9035762

Cheers,
Peter

**Comment by MarcoEidinger** [comment]
Thanks Peter, that helped me! Awesome :)
